[mypy]
python_version = 3.9
warn_unused_configs = True
show_error_codes = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-metaphone.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-mlflow.*]
ignore_missing_imports = True

[mypy-pyarabic.*]
ignore_missing_imports = True

[mypy-w3lib.*]
ignore_missing_imports = True

[mypy-arabicstopwords.*]
ignore_missing_imports = True
